### ISSUE TITLE
Initialization error: Wrong application id.

### ISSUE THREAD

**Issue by nnetsys** [kavolorn/VK-ANE#2]
After starting the app, an error occurs:
Initialization error: Wrong application id.

applicationId is 4620596, os: Android

debug trace:

[Starling] Initialization complete.
[Starling] Display Driver: OpenGL (Baseline Constrained)
1648 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object VigilanceExtension]
1659 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object InjectableLoggerExtension]
1661 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object ContextViewExtension]
1663 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object EventDispatcherExtension]
1665 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object ModularityExtension]
1669 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object DirectCommandMapExtension]
1674 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object EventCommandMapExtension]
1678 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object LocalEventMapExtension]
1680 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object StarlingEventMapExtension]
1686 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object ViewManagerExtension]
1694 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object StageObserverExtension]
1696 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object MediatorMapExtension]
1699 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object ViewProcessorMapExtension]
1705 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object StageCrawlerExtension]
1707 DEBUG Context-0-8a [object ExtensionInstaller] Installing extension [object StageSyncExtension]
1709 DEBUG Context-0-8a [object ConfigManager] Not yet initialized. Queuing config class [class ContextViewListenerConfig]
1710 DEBUG Context-0-8a [object ConfigManager] Not yet initialized. Queuing config class [class Configuration]
1713 DEBUG Context-0-8a [object ConfigManager] Not yet initialized. Queuing config object [object ContextView]
1715 DEBUG Context-0-8a [object ContextViewExtension] Mapping [object ApplicationView] as contextView
1718 DEBUG Context-0-8a [object ModularityExtension] Context has a ViewManager. Configuring view manager based context existence watcher...
1734 DEBUG Context-0-8a [object ModularityExtension] Context view is not yet on stage. Waiting...
1735 DEBUG Context-0-8a [object StageSyncExtension] Context view is not yet on stage. Waiting...
1742 DEBUG Context-0-8a [object ModularityExtension] Context view is now on stage. Continuing...
1743 DEBUG Context-0-8a [object ModularityExtension] Context configured to inherit. Broadcasting existence event...
1745 DEBUG Context-0-8a [object StageSyncExtension] Context view is now on stage. Initializing context...
1750 INFO Context-0-8a Context-0-8a Initializing...
1791 DEBUG Context-0-8a [object StageObserverExtension] Creating genuine StageObserver Singleton
1793 DEBUG Context-0-8a [object ConfigManager] Now initializing. Instantiating config class [class ContextViewListenerConfig]
1801 DEBUG Context-0-8a [object ViewManagerBasedExistenceWatcher] Adding context existence event listener to container [object ApplicationView]
1801 DEBUG Context-0-8a [object ConfigManager] Now initializing. Instantiating config class [class Configuration]
[ru.kavolorn.ane.VK] Constructing VK extension.
[ru.kavolorn.ane.VK] VK::initialize() is being executed.
[ru.kavolorn.ane.VK] VK::isSupported() is being executed.
[ru.kavolorn.ane.VK] VK::setAuthorizeParameters() is being executed.
[ru.kavolorn.ane.VK] VK::isSupported() is being executed.
3990 DEBUG Context-0-8a [object ConfigManager] Now initializing. Injecting into config object [object ContextView]
3993 INFO Context-0-8a Context-0-8a Initialize complete
3995 DEBUG Context-0-8a [object StageCrawlerExtension] ViewManager is installed. Checking for managed containers...
3996 DEBUG Context-0-8a [object StageCrawlerExtension] StageCrawler scanning container [object ApplicationView] ...
4003 DEBUG Context-0-8a [object StageCrawlerExtension] StageCrawler finished scanning [object ApplicationView]
[ru.kavolorn.ane.VK] VK::statusHandler() is being executed.
Initialization error: Wrong application id.

**Comment by kavolorn** [comment]
Hello, thank you for your comment! I think there is misunderstanding in term application id. I should describe it more precisely somewhere or even change error message.

You receive error about package id (thought you see words "application id"). License key in this demo is linked with package id ru.kavolorn.ane.VK.Demo and you can change it only with your own license key. 

However you can leave this package id and configure you own application in vk.com/dev with this package id and your own fingerprint. You will have your own application id (vk application id). This kind of setup will work for test purpose.

Feel free to write questions if I badly explained the current problem.

**Comment by sashkooo** [comment]
Hi Alexey! I created new app in Google Play Developer Console, and get license key from new app settings. But with new key I have an error:
[trace] Initialization error: Wrong license key.
Is it right way to get license key that I need? You said that your license key is linked with package "ru.kavolorn.ane.VK.Demo", but when I created app in Developer Console, the new license key was available before i upload apk. So how I can link my package id to license key?

**Comment by kavolorn** [comment]
Hi sashkoo,

License key for your app package should be ordered from https://kavolorn.ru/pro-native-extensions/ service. It is not license key from Google. It is a license for ANE itself.

**Comment by sashkooo** [comment]
Ok. I tried to follow your comment, and changed my app id to ru.kavolorn.ane.VK.Demo and got this error:
[trace] Initialization error: Wrong application id.
Then I tried to run your demo from this repo without changing any code, and it throws the same error
[trace] Initialization error: Wrong application id.

**Comment by kavolorn** [comment]
I assume you're running demo on Android device. And I think you see error because your IDE adds prefix "air." or suffix ".debug" for application ID.

## How to disable "air." prefix

To disable "air." prefix you should define AIR_NOANDROIDFLAIR environment variable and set it to `true`. On my mac I use this command: `launchctl setenv AIR_NOANDROIDFLAIR "true"`. Instructions for Windows you can find here: http://www.computerhope.com/issues/ch000549.htm.

After you have done it you should restart your IDE as well.

## How to disable ".debug" suffix

Flash Builder adds this suffix in run configuration dialog. You should go there and remove .debug. Example of run configuration dialog;

![testfb47main](https://cloud.githubusercontent.com/assets/2448274/6844678/c454645e-d3b5-11e4-87ae-93709b1056ce.png)

## If it is not working

Check your bin/ folder. Application descriptor file sometimes is not updated by Flash Builder.

**Comment by sashkooo** [comment]
Adding AIR_NOANDROIDFLAIR variable fixes the problem with id, but using this parameter the debugger in my IDE (IntelliJ Idea) can not connect application to debug on device. (Seems it not support missing air. prefix)
Next problem. Whan I clicked wall post button in the demo, I got error on Android 4.0.2:
https://drive.google.com/file/d/0B5BMr8MsRnnEOHNfYkptb1JTNHo3S0d4a0ZwTHB1MG91bVV3/view?usp=sharing
and blank page on Android 2.3.7
https://drive.google.com/file/d/0B5BMr8MsRnnEd0RpVXVNWS00Snc/view

**Comment by kavolorn** [comment]
So, ANE is initialised correctly. Now you have problem with certificate fingerprint. I did not publish my own certificate here because it was not necessary before. Looks like I have to do it now.

**Comment by kavolorn** [comment]
I have no problems with IntelliJ Idea. I use it as my primary IDE.

**Comment by sashkooo** [comment]
I fixed problem with connection to debugger by delete and recreate project module (seems air prefix was linked in hidden module settings)

**Comment by kavolorn** [comment]
Ok! By the way, you can provide your fingerprint to me. I will put it to VK demo app settings. It will take less time than prepare and publish my certificate.

**Comment by sashkooo** [comment]
2CD563B3A4B7079C571DE069EE80EE7990BE4A6A
Can you provide instructions where it have to be in settings?

Also, it looks like open WebView for autorization, but I have installed VK app. Is the extension support connecting directly to VK APP?

**Comment by kavolorn** [comment]
I've put your fingerprint in my demo app setup in VK development site. Now your error with fingerprint should be gone. About VK side setup you can read here https://vk.com/dev. It is not so difficult.

This is what I have for demo app:

![screen shot 2015-03-26 at 19 36 41](https://cloud.githubusercontent.com/assets/2448274/6852791/892c35a2-d3ef-11e4-9111-c8d474e32268.png)

**Comment by kavolorn** [comment]
On my iOS device I use app authorization. On Android device I haven't tested it. I assume that it should work.

**Comment by sashkooo** [comment]
Can you also help me how to use correct keystore file. I got this fingerprint by instruction from this article:
http://interosite.ru/articles/rabota-s-api-vkontakte-v-android
using command
keytool -exportcert -alias androiddebugkey -keystore /c/Users/sashkooo/.android/debug.keystore -list -v
It was work fine with default password "android".
But when I tried to use this file for package air application, this password is not working:
http://gyazo.com/40f358652e17820afae9fa1a92d16a1e

**Comment by sashkooo** [comment]
Looks like I have to configure this lines
http://gyazo.com/d9d21ad5903d45519901433a994569e4
by this information
http://gyazo.com/17810d527633a6e973cd57eec093f291
can you help?

**Comment by sashkooo** [comment]
All works now, thanks.

**Comment by kavolorn** [comment]
Nice to hear :)

**Comment by Rasalexman** [comment]
Hi kavalorn, i have the same problem with ur sdk, but i also do everything correct like in tutorial. I have a licence key for my app and i set all nessary setting into my vk standalone application (eg fingerprint and activity ets... correct), also i have already uploaded app into GooglePlay market and it's with "air." - prefix. Sorry for my eng. What can i do to fix this problem "Initialization error:,Wrong application id."

**Comment by kavolorn** [comment]
Hi there,
Have you added you application bundle ID in you license key? Interfaces are here: http://kavolorn.ru/pro-native-extensions/en

**Comment by kavolorn** [comment]
I see you problem. You should insert applicationId (bundle id of you apk, same as in google play url) in the licence key. I will clean you records in database.
