### ISSUE TITLE
App crash when turned off Wi-Fi

### ISSUE THREAD

**Issue by sashkooo** [kavolorn/VK-ANE#3]
03-26 18:07:38.647 D/[ru.kavolorn.ane.VK](24478): ru.kavolorn.ane.VKExecuteFunction$1.onError() Is being executed. Error code is -105
03-26 18:07:38.655 D/AndroidRuntime(24478): Shutting down VM
03-26 18:07:38.655 W/dalvikvm(24478): threadid=1: thread exiting with uncaught exception (group=0x40015610)
03-26 18:07:38.663 E/AndroidRuntime(24478): FATAL EXCEPTION: main
03-26 18:07:38.663 E/AndroidRuntime(24478): java.lang.NullPointerException
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at ru.kavolorn.ane.VKExecuteFunction$1.onError(VKContext.java:110)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at com.vk.sdk.api.VKRequest$2.run(VKRequest.java:417)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at android.os.Handler.handleCallback(Handler.java:587)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at android.os.Handler.dispatchMessage(Handler.java:92)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at android.os.Looper.loop(Looper.java:130)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at android.app.ActivityThread.main(ActivityThread.java:3703)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at java.lang.reflect.Method.invoke(Method.java:507)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
03-26 18:07:38.663 E/AndroidRuntime(24478): 	at dalvik.system.NativeStart.main(Native Method)
03-26 18:07:38.679 D/dalvikvm(24085): GC_FOR_MALLOC freed 547K, 53% free 2759K/5831K, external 0K/0K, paused 163ms

**Comment by kavolorn** [comment]
Thanks for reporting! I will check the code.

**Comment by kavolorn** [comment]
Bug if fixed in 1.0.1 update.
