### ISSUE TITLE
Wall post dialog

### ISSUE THREAD

**Issue by sashkooo** [kavolorn/VK-ANE#5]
Can I preview wall post dialog, or only post instantly using wall.post command? If not, can you add support? It seems to be used VKShareDialog and VKShareDialogController classes from vk-android-sdk and vk-ios-sdk.

**Comment by kavolorn** [comment]
I have not integrated this dialogs yet. But I was thinking about it and I will add it to future plans.

**Comment by sashkooo** [comment]
can you provide dates when you can do it?

**Comment by kavolorn** [comment]
It depends if someone needs it or not. Do you have a request for this feature? I can make it in about a week or two I think.

**Comment by sashkooo** [comment]
Sorry, my client rejected request of VK support. Maybe it is temporary. I will tell you if I need this feature in future.

**Comment by kavolorn** [comment]
Sure, no problem. Thank you for useful feedback!

**Comment by kavolorn** [comment]
Support for native dialogs was added in 2.0.0 release.
