### ISSUE TITLE
invalid_client error from VK on Ios

### ISSUE THREAD

**Issue by Rasalexman** [kavolorn/VK-ANE#7]
Hello kavolorn !!! I have some troubles with VK.getInstance().authorize method. It's return to me 
"error:invalid_client, error_description:client_idis incorrect" in web view on IOS and my app going to crash on some devices like Samsung Galaxy S4. Please help me to correct my actions.

i have good initialized but then it's crashed !!!

// Extension was successfully initialized
        VK.getInstance().addEventListener(VKEvent.INITIALIZATION_SUCCESS, function (event:VKEvent):void
        {
            AppLog.tr("Initialization success:", event.message);
            AppLog.tr("Current SDK version:", VK.getInstance().getSdkVersion());
            AppLog.tr("Current API version:", VK.getInstance().getApiVersion());

```
        VK.getInstance().authorize([
            VKScope.WALL,
            VKScope.FRIENDS
        ], true, false, false);
    });
```

**Comment by kavolorn** [comment]
Привет

Я написал на почту из аккаунта, но ответа не получил. Можно по-русски, чтобы было понятней.

Прежде всего об ошибке. Это ошибка OAuth 2.0 протокола, т.е. связана она с авторизацией. Откуда может идти проблема?
1. Неверный applicationId (тот который у тебя с air.\* начинается на андроиде, может не начинаться с air.\* на иосе). Это скорей всего наиболее вероятная ошибка. Проверь это. Для полного контроля идишника используй AIR_NOANDROIDFLAIR false переменную окружения (почитай про нее в документах адоби).
2. Краш приложения может быть связан с тем, что не хватает какого-либо слушателя событий. Поставь, пожалуйста, все как в демо для того чтобы быть в этом уверенным.

Больше пока что ничего не могу сказать, нужно больше информации.

**Comment by kavolorn** [comment]
No further information provided.
